"""movies table

Revision ID: 05f83f96f0b4
Revises: 
Create Date: 2022-08-30 22:10:21.500646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f83f96f0b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('custom_input', sa.Boolean(), nullable=True),
    sa.Column('imdb', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
