"""changed lazy to dynamic

Revision ID: 41a5c5b78803
Revises: a0a148473d84
Create Date: 2022-09-14 22:48:19.291022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a5c5b78803'
down_revision = 'a0a148473d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_list', 'm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_list', 'u_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_list', 'u_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_list', 'm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
