"""changed lazy to dynamic

Revision ID: a0a148473d84
Revises: eb2fae58520a
Create Date: 2022-09-14 22:45:12.171171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a148473d84'
down_revision = 'eb2fae58520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_list', 'm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_list', 'u_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_list', 'u_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_list', 'l_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_list', 'm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
