"""all (rough) tables implemented

Revision ID: afaa5a1f6ef3
Revises: 05f83f96f0b4
Create Date: 2022-09-06 19:56:21.086657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afaa5a1f6ef3'
down_revision = '05f83f96f0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie_list',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('l_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['l_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['m_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('m_id', 'l_id')
    )
    op.create_table('user_list',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('l_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['l_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('u_id', 'l_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_list')
    op.drop_table('movie_list')
    op.drop_table('user')
    op.drop_table('list')
    # ### end Alembic commands ###
